## Load in NumPy (numpy has already been installed)


In [ ]:
import numpy as np


## The Basics

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)


[1 2 3]


In [ ]:
#Get Dimension
a.ndim

1

In [ ]:
#Get Shape
a.shape

(3,)

In [ ]:
#Get Type
a.dtype

dtype('int64')

In [ ]:
b = np.array([[9.0, 8.0, 7.0], [6.0,5.0,4.0]])
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Get Dimension
b.ndim

2

In [ ]:
#Get shape
b.shape

(2, 3)

In [ ]:
#Get Size
a.itemsize
        

2

In [ ]:
#Get total size
a.size * a.itemsize
a.nbytes


6

In [ ]:
b.itemsize

8

# Accessing/Changingspecific elements, rows, colums, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element [r, c]
a[1,5]

13

In [ ]:
#Get a specific element [r, c]
a[1,-2]

13

In [ ]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a speific column
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
#In the first row with index 0, between numbers at index 1 and 6 (last number is exlusive), step size 2 ie every second value
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]. Note -1 is exclusive
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
#3D example


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (work outside in)
b[0,1,1]

4

In [ ]:
#replace. Create a subsequence of same dimension
b[:,1,:] = [[9,9],[8,8]]

In [ ]:
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [ ]:
import numpy as np
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#2D shape 2x3
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#3D shape 2 x 3 x 3
np.zeros((2,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#4D shape 2 x 3 x 3 x 2
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#All 1s matrix 
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#3 Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Any other number (full_like) method allows us to take a shape that has already been created. Pass in array "a", created above.
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#intitialise a matrix of random decimal numbers
np.random.rand(4,2)

array([[0.35341421, 0.74195923],
       [0.72854754, 0.97361264],
       [0.31158874, 0.38443572],
       [0.40507178, 0.52782337]])

In [ ]:
#random decimal numbers passing in a shape
np.random.random_sample(a.shape)

array([[0.34813979, 0.65862403, 0.44778979, 0.26402177, 0.83300479,
        0.52537996, 0.55180952],
       [0.72015434, 0.6967537 , 0.54943796, 0.43207616, 0.68861772,
        0.3007983 , 0.21461482]])

In [ ]:
#Random Integer Values. Specify start value as 7, specify a size
np.random.randint(7, size=(3,3))

array([[2, 0, 3],
       [0, 0, 0],
       [0, 6, 2]])

In [ ]:
#identiy matrix by its nature wil be a square matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
#Repeat an array
import numpy as np
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
#1:-1 from the first element to the last element
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!

In [17]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
#the issue is that a has also mutated. The variable b points to the same thing as a. We didn't tell numpy to make a copy of a.
print(a)

[100   2   3]
[100   2   3]


In [2]:
#Make a copy of the array using the copy() function
import numpy as np
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics


In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2


array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2


array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [10]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [11]:
#cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [15]:
#matrix row and column
a = np.ones((2,3))
print(a)
#the columns of the first matrix must equal the rows of the second matrix.
b = np.full((3,2),5)
print(b)

# Multiply. Should have a 2x2 matrix at the end. Matric multiply function matmul(a,b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


array([[15., 15.],
       [15., 15.]])

In [17]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [18]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Singular vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc ...

# Statistics

In [19]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.min(stats)

1

In [22]:
np.max(stats)

6

In [23]:
np.max(stats, axis=0)

array([4, 5, 6])

In [24]:
np.min(stats, axis=0)

array([1, 2, 3])

In [25]:
np.max(stats, axis=1)
# 3 and 6 are the biggest values

array([3, 6])

In [29]:
#sum up all terms. 
np.sum(stats)

21

In [30]:
#Can go by row or column using axis
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganising Arrays

In [32]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

#the original and reshape must contain the same number of values otherwise you will get an error

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [34]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Load Data from File

In [43]:
#import data from txt file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') #this makes a copy with int32 data type
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  83]]


### Boolean Masking and Advanced Indexing
    

In [44]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [45]:
filedata >= 20


array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [46]:
#make an array from the file data but onlyinclude data where the value is greater than 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  83], dtype=int32)

In [47]:
## You can index with a list in NumPy
#pass in a list array and index
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [49]:
#what columns have a value greater than 50
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [52]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [53]:
#not greater than 50 and less than 100 ~

(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## QUIZ

###### Index values in matrix located at:
- row 2, 3
- column 0,1

a[2:4, 0:2]

###### In a 5 x 6 matrix with values 1 to 30. Index values diagonally left to right and down [2,8,14,20]
values at index row and column:
- 0,1
- 1,2
- 2,3
- 3,4

a[[0,1,2,3],[1,2,3,4]]

###### index values at indexes row and column;
- 0,3
- 0,4
- 4,3
- 4,4
- 5,3
- 5,4

a[[0,0,4,4,5,5],[3,4,3,4,3,4]]

i.e. the 0, 4, 5 index rows & column index 3 onwards
a[[0,4,5], 3:]